variables:
  NODE_VERSION: "4.4.7"

before_script:
  - docker pull docker.savicontrols.local/node-build:${NODE_VERSION}

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - cedia_followup/node_modules/

test-build:
  script:
   - cd cedia_followup
   - npm install
   - npm test
